# Generated by Django 5.1.7 on 2026-06-09 07:47

import django.db.models.deletion
import profiles.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Lawyer', 'Lawyer'), ('Notary', 'Notary'), ('Accountant', 'Accountant'), ('Translator', 'Translator')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True, null=True)),
                ('file', models.URLField(max_length=500)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('icon_url', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.URLField(max_length=500)),
                ('file_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Media',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
            },
        ),
        migrations.CreateModel(
            name='VendorLegalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_id', models.CharField(max_length=100)),
                ('last_name_id', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('bar_association', models.CharField(blank=True, choices=[('Alba Bar Association', 'Alba Bar Association'), ('Arad Bar Association', 'Arad Bar Association'), ('Arges Bar Association', 'Arges Bar Association'), ('Bacau Bar Association', 'Bacau Bar Association'), ('Bihor Bar Association', 'Bihor Bar Association'), ('Bistrita-Nasaud Bar Association', 'Bistrita-Nasaud Bar Association'), ('Botosani Bar Association', 'Botosani Bar Association'), ('Braila Bar Association', 'Braila Bar Association'), ('Brasov Bar Association', 'Brasov Bar Association'), ('Bucharest Bar Association', 'Bucharest Bar Association'), ('Buzau Bar Association', 'Buzau Bar Association'), ('Caras-Severin Bar Association', 'Caras-Severin Bar Association'), ('Calarasi Bar Association', 'Calarasi Bar Association'), ('Cluj Bar Association', 'Cluj Bar Association'), ('Constanta Bar Association', 'Constanta Bar Association'), ('Covasna Bar Association', 'Covasna Bar Association'), ('Dambovita Bar Association', 'Dambovita Bar Association'), ('Dolj Bar Association', 'Dolj Bar Association'), ('Galati Bar Association', 'Galati Bar Association'), ('Giurgiu Bar Association', 'Giurgiu Bar Association'), ('Gorj Bar Association', 'Gorj Bar Association'), ('Harghita Bar Association', 'Harghita Bar Association'), ('Hunedoara Bar Association', 'Hunedoara Bar Association'), ('Ialomita Bar Association', 'Ialomita Bar Association'), ('Iasi Bar Association', 'Iasi Bar Association'), ('Ilfov Bar Association', 'Ilfov Bar Association'), ('Maramures Bar Association', 'Maramures Bar Association'), ('Mehedinti Bar Association', 'Mehedinti Bar Association'), ('Mures Bar Association', 'Mures Bar Association'), ('Neamt Bar Association', 'Neamt Bar Association'), ('Olt Bar Association', 'Olt Bar Association'), ('Prahova Bar Association', 'Prahova Bar Association'), ('Salaj Bar Association', 'Salaj Bar Association'), ('Satu Mare Bar Association', 'Satu Mare Bar Association'), ('Sibiu Bar Association', 'Sibiu Bar Association'), ('Suceava Bar Association', 'Suceava Bar Association'), ('Teleorman Bar Association', 'Teleorman Bar Association'), ('Timis Bar Association', 'Timis Bar Association'), ('Tulcea Bar Association', 'Tulcea Bar Association'), ('Valcea Bar Association', 'Valcea Bar Association'), ('Vaslui Bar Association', 'Vaslui Bar Association'), ('Vrancea Bar Association', 'Vrancea Bar Association')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('avatar_url', models.URLField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=50, null=True)),
                ('facebook', models.URLField(blank=True, max_length=255, null=True)),
                ('youtube', models.URLField(blank=True, max_length=255, null=True)),
                ('instagram', models.URLField(blank=True, max_length=255, null=True)),
                ('twitter', models.URLField(blank=True, max_length=255, null=True)),
                ('social_media_status', models.BooleanField(default=False)),
                ('general_link', models.URLField(blank=True, max_length=255, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileCompletionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=profiles.models._generate_session_token, max_length=64, unique=True)),
                ('business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('avatar_url', models.URLField(blank=True, max_length=255, null=True)),
                ('first_name_id', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name_id', models.CharField(blank=True, max_length=100, null=True)),
                ('legal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('bar_association', models.CharField(blank=True, max_length=50, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=50, null=True)),
                ('facebook', models.URLField(blank=True, max_length=255, null=True)),
                ('youtube', models.URLField(blank=True, max_length=255, null=True)),
                ('instagram', models.URLField(blank=True, max_length=255, null=True)),
                ('twitter', models.URLField(blank=True, max_length=255, null=True)),
                ('social_media_status', models.BooleanField(default=False)),
                ('general_link', models.URLField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(default=profiles.models._default_session_expiry)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.address')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.category')),
                ('languages', models.ManyToManyField(blank=True, to='profiles.language')),
            ],
        ),
    ]
