# Generated by Django 5.1.7 on 2026-06-09 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profilecompletionsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='profiles.servicecategory'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.address'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.category'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='languages',
            field=models.ManyToManyField(blank=True, to='profiles.language'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorlegalinfo',
            name='vendor_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.vendorprofile'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='vendor_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_categories', to='profiles.vendorprofile'),
        ),
        migrations.AddField(
            model_name='service',
            name='vendor_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='profiles.vendorprofile'),
        ),
        migrations.AddField(
            model_name='media',
            name='vendor_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='profiles.vendorprofile'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='vendor_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='profiles.vendorprofile'),
        ),
    ]
