# Generated by Django 5.1.7 on 2026-06-09 07:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('start_datetime', models.DateTimeField(db_index=True)),
                ('end_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('rescheduled', 'Rescheduled'), ('interrupted', 'Interrupted'), ('failed', 'Failed'), ('no_show', 'No Show')], db_index=True, default='pending', max_length=20)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('is_rescheduled', models.BooleanField(default=False)),
                ('last_rescheduled_at', models.DateTimeField(blank=True, null=True)),
                ('refund_status', models.CharField(choices=[('none', 'No Refund'), ('pending', 'Refund Pending'), ('approved', 'Refund Approved'), ('rejected', 'Refund Rejected'), ('not_applicable', 'Not Applicable')], db_index=True, default='none', max_length=20)),
                ('refund_reason', models.TextField(blank=True, null=True)),
                ('refund_requested_at', models.DateTimeField(blank=True, null=True)),
                ('refund_response', models.TextField(blank=True, null=True)),
                ('refund_processed_at', models.DateTimeField(blank=True, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Total price paid for this appointment', max_digits=10)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Platform commission amount', max_digits=10)),
                ('lawyer_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount lawyer receives', max_digits=10)),
                ('stripe_payment_intent_id', models.CharField(blank=True, help_text='Stripe Payment Intent ID for paid appointments', max_length=255, null=True)),
                ('payment_task_id', models.CharField(blank=True, help_text='Celery task ID for payment timeout deletion', max_length=255, null=True)),
                ('reminder_task_id', models.CharField(blank=True, help_text='Celery task ID for appointment reminder', max_length=255, null=True)),
                ('auto_complete_task_id', models.CharField(blank=True, help_text='Celery task ID for auto-completion', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('lawyer', 'Lawyer'), ('client', 'Client')], max_length=20)),
                ('attended', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('participant_notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agora_channel_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('agora_token', models.CharField(blank=True, max_length=512, null=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('active', 'Active'), ('ended', 'Ended')], default='not_started', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('actual_duration_minutes', models.IntegerField(blank=True, null=True)),
                ('session_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
