# Generated by Django 5.1.7 on 2026-06-09 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lawyer', '0002_initial'),
        ('lawyer_appointment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='lawyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='lawyer.lawyerprofile'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='offering_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lawyer.offeringtype'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='rescheduled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointmentparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointmentsession',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='lawyer_appointment.appointment'),
        ),
        migrations.AddField(
            model_name='appointmentparticipant',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='lawyer_appointment.appointmentsession'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['lawyer', 'start_datetime', 'status'], name='lawyer_appo_lawyer__28b68d_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['client', 'start_datetime'], name='lawyer_appo_client__760ccf_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['refund_status'], name='lawyer_appo_refund__642b49_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status', 'start_datetime'], name='lawyer_appo_status_c167a2_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointmentparticipant',
            constraint=models.UniqueConstraint(fields=('session', 'user'), name='unique_session_user'),
        ),
    ]
