# Generated by Django 5.1.7 on 2026-06-09 07:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lawyer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], db_index=True, help_text='0=Monday, 1=Tuesday, ... 6=Sunday')),
                ('start_time', models.TimeField(help_text='Start time for availability (e.g., 09:00)')),
                ('end_time', models.TimeField(help_text='End time for availability (e.g., 17:00)')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this availability slot is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='lawyer.lawyerprofile')),
                ('offering', models.ForeignKey(help_text='The pricing plan/offering associated with this availability slot', on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='lawyer.lawyeroffering')),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
                'indexes': [models.Index(fields=['lawyer', 'day_of_week', 'is_active'], name='avail_lawyer_day_active_idx'), models.Index(fields=['day_of_week', 'start_time'], name='avail_day_start_idx'), models.Index(fields=['offering', 'is_active'], name='avail_offering_active_idx'), models.Index(fields=['lawyer', 'offering', 'day_of_week'], name='avail_lawyer_offering_day_idx')],
                'constraints': [models.UniqueConstraint(fields=('lawyer', 'day_of_week', 'start_time', 'end_time', 'offering'), name='unique_lawyer_schedule_slot')],
            },
        ),
        migrations.CreateModel(
            name='Unavailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, help_text='Date of unavailability')),
                ('start_time', models.TimeField(blank=True, help_text='Start time (leave blank for all-day unavailability)', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='End time (leave blank for all-day unavailability)', null=True)),
                ('is_all_day', models.BooleanField(default=False, help_text='Whether this is an all-day unavailability')),
                ('unavailability_type', models.CharField(choices=[('vacation', 'Vacation'), ('sick_leave', 'Sick Leave'), ('personal', 'Personal'), ('court_appearance', 'Court Appearance'), ('meeting', 'Meeting'), ('training', 'Training'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Optional reason for unavailability', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailabilities', to='lawyer.lawyerprofile')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'indexes': [models.Index(fields=['lawyer', 'date'], name='unavail_lawyer_date_idx'), models.Index(fields=['date', 'start_time'], name='unavail_date_start_idx'), models.Index(fields=['lawyer', 'unavailability_type'], name='unavail_lawyer_type_idx')],
            },
        ),
    ]
