# Generated by Django 5.1.7 on 2026-06-09 07:47

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LawyerCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Lawyer Categories',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='LawyerOffering',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text='Pricing plan name (e.g., Standard plan, Weekend plan, Premium plan)', max_length=255)),
                ('price_per_30min', models.DecimalField(decimal_places=2, default=Decimal('200.00'), help_text='Base price for 30 minutes in USD', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LawyerSubcategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Lawyer Subcategories',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='OfferingType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('physical', 'Physical'), ('audio', 'Audio'), ('video', 'Video')], db_index=True, max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='LawyerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_number', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('fiscal_code', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('kyc_verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], db_index=True, default='unverified', max_length=20)),
                ('legal_verified', models.BooleanField(default=False)),
                ('cancellation_threshold_hours', models.IntegerField(default=24, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(168)])),
                ('average_rating', models.DecimalField(db_index=True, decimal_places=2, default=Decimal('0.00'), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('review_count', models.IntegerField(db_index=True, default=0)),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Platform commission percentage (e.g., 10.00 for 10%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_pricing_plan', models.ForeignKey(blank=True, help_text='Default pricing plan used when no specific plan is set', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_lawyers', to='lawyer.lawyeroffering')),
                ('lawyercategories', models.ManyToManyField(blank=True, related_name='lawyer_profiles', to='lawyer.lawyercategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
