# Generated by Django 5.1.7 on 2026-06-09 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lawyer', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyerprofile',
            name='vendor_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_profile', to='profiles.vendorprofile'),
        ),
        migrations.AddField(
            model_name='lawyeroffering',
            name='lawyer_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='lawyer.lawyerprofile'),
        ),
        migrations.AddField(
            model_name='lawyersubcategory',
            name='lawyercategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='lawyer.lawyercategory'),
        ),
        migrations.AddField(
            model_name='lawyerprofile',
            name='lawyersubcategories',
            field=models.ManyToManyField(blank=True, related_name='lawyer_profiles', to='lawyer.lawyersubcategory'),
        ),
        migrations.AddField(
            model_name='offeringtype',
            name='offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offering_types', to='lawyer.lawyeroffering'),
        ),
        migrations.AddIndex(
            model_name='lawyeroffering',
            index=models.Index(fields=['is_active', 'lawyer_profile'], name='loff_active_prof_idx'),
        ),
        migrations.AddIndex(
            model_name='lawyeroffering',
            index=models.Index(fields=['lawyer_profile', 'is_active', 'name'], name='loff_prof_active_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='lawyeroffering',
            constraint=models.UniqueConstraint(fields=('lawyer_profile', 'name'), name='unique_lawyer_profile_name'),
        ),
        migrations.AddIndex(
            model_name='lawyersubcategory',
            index=models.Index(fields=['lawyercategory', 'title'], name='lsubcat_cat_title_idx'),
        ),
        migrations.AddIndex(
            model_name='lawyerprofile',
            index=models.Index(fields=['kyc_verification_status', 'average_rating'], name='lprof_kyc_rating_idx'),
        ),
        migrations.AddIndex(
            model_name='lawyerprofile',
            index=models.Index(fields=['vendor_profile', 'kyc_verification_status'], name='lprof_vendor_kyc_idx'),
        ),
        migrations.AddIndex(
            model_name='lawyerprofile',
            index=models.Index(fields=['-created_at'], name='lprof_created_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='offeringtype',
            index=models.Index(fields=['offering', 'is_active'], name='otype_offering_active_idx'),
        ),
        migrations.AddIndex(
            model_name='offeringtype',
            index=models.Index(fields=['type', 'is_active'], name='otype_type_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='offeringtype',
            constraint=models.UniqueConstraint(fields=('offering', 'type'), name='unique_offering_type'),
        ),
    ]
