# Generated by Django 5.1.7 on 2026-06-09 07:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KYCVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_verification_session_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('status', models.CharField(choices=[('requires_input', 'Requires Input'), ('processing', 'Processing'), ('verified', 'Verified'), ('canceled', 'Canceled')], default='requires_input', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'KYC Verification',
                'verbose_name_plural': 'KYC Verifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
