# Generated by Django 5.1.7 on 2026-06-09 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kyc', '0001_initial'),
        ('lawyer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycverification',
            name='lawyer_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_verification', to='lawyer.lawyerprofile'),
        ),
    ]
